# -*- coding: utf-8 -*-
DEBUG_MESSAGE = "[[TELEGRAM DEBUG]]\nUserFirst: {}\nUserId: {}\nMessage: {}\nChatTitle: {}\nChatId: {}"
SERVER_MESSAGE="<b>SERVER STATUS</b>\n<b>CPU:</b> <code>{cpu}%</code>\n<b>RAM:</b> <code>{ram}%</code>"
DEFAULT_WELCOME="Ti diamo il Benvenuto {username} su {chat}"
BOT_WELCOME = "Grazie per avermi aggiunta al gruppo {}\nPer funzionare correttamente devi farmi admin!"
INSERT_W = "<b>Attenzione non puoi inserire un welcome vuoto!\nISTRUZIONI: Puoi utilizzare i seguenti parametri:\n <code>{username};{first_name};{chat_name}</code></b>"
GET_MESSAGE = "<b>INFORMAZIONI UTENTE</b>\n\nUSERNAME: {username}\nID: <code>{id}</code>\nGRUPPO: {chat_title}\nCHAT_ID: <code>{idchat}</code>"
MESSAGE_SB = "Devi specificare un motivo per il SuperBan!"
RULES_MESSAGE = "Non hai impostato nessun <b>regolamento</b> per questa chat!\nUtilizza il comando /setrules per impostare il regolamento."
RULES_HELP = "Devi inserire un testo! non può essere vuoto!"
BUTTONS_INSERT = "Non puoi inserire bottoni vuoti!\nFormato per inserire i bottoni: /add NOMEBOTTONE,url\nESEMPIO: <code>/add CIAO,https://google.it</code>"
#### WARN TEXT ####
WARN_START = "L'utente {} è stato inserito nel database con 1 Warn"
WARN_1 = "{} Sei stato warnato 1 volta"
WARN_2 = "{} Sei stato warnato 2 volte"
WARN_END = "{} è stato bannato dopo 3 warn"